# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

strategy:
  matrix:
    linux-perl530:
        PERL_VERSION: '5.30.2'
        IMAGE: 'ubuntu-latest'
    linux-perl528:
        PERL_VERSION: '5.28.2'
        IMAGE: 'ubuntu-latest'
    linux-perl526:
        PERL_VERSION: '5.26.3'
        IMAGE: 'ubuntu-latest'
    linux-perl524:
        PERL_VERSION: '5.24.4'
        IMAGE: 'ubuntu-latest'
    linux-perl522:
        PERL_VERSION: '5.22.4'
        IMAGE: 'ubuntu-latest'
    macos-perl530:
        PERL_VERSION: '5.30.2'
        IMAGE: 'macos-latest'
    macos-perl528:
        PERL_VERSION: '5.28.2'
        IMAGE: 'macos-latest'
    macos-perl526:
        PERL_VERSION: '5.26.3'
        IMAGE: 'macos-latest'
    macos-perl524:
        PERL_VERSION: '5.24.4'
        IMAGE: 'macos-latest'
    macos-perl522:
        PERL_VERSION: '5.22.4'
        IMAGE: 'macos-latest'

pool:
  vmImage: $(IMAGE)

steps:
- script: |
    sudo apt-get install build-essential curl file git
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
    export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
    brew install libarchive
  displayName: 'Install dependencies (Ubuntu)'
  condition: startsWith(variables['IMAGE'], 'ubuntu')

- script: |
    HOMEBREW_NO_AUTO_UPDATE=1 brew install libarchive
  displayName: 'Install macOS dependencies'
  condition: startsWith(variables['IMAGE'], 'macos')

- script: |
    PATH=~/perl5/bin:~/perl5/perlbrew/bin:~/perl5/perlbrew/perls/perl-$(PERL_VERSION)/bin:$PATH
    echo "##vso[task.setvariable variable=PATH]$PATH"
    wget -O - https://install.perlbrew.pl | bash
    perlbrew install --notest perl-$(PERL_VERSION)
    perl -V
    curl -L https://cpanmin.us | perl - App::cpanminus
  condition: or(startsWith(variables['IMAGE'], 'ubuntu'), startsWith(variables['IMAGE'], 'macos'))
  displayName: 'Install perl (Unix)'

- script: |
    cpanm --quiet --notest Dist::Zilla Dist::Zilla::PluginBundle::Author::JACQUESG App::Ack
    dzil authordeps --missing | ack -v "inc::" | cpanm --quiet --notest
    dzil listdeps --missing | cpanm --quiet --notest
  condition: or(startsWith(variables['IMAGE'], 'ubuntu'), startsWith(variables['IMAGE'], 'macos'))
  displayName: 'Install CPAN dependencies (Unix)'

- script: |
    dzil cover -ignore_re ^deps -ignore_re CORE -ignore_re ^const -ignore_re usr -test -report coveralls
  condition: startsWith(variables['IMAGE'], 'ubuntu')
  env:
    COVERALLS_REPO_TOKEN: $(COVERALLS_TOKEN)
    RELEASE_TESTING: 1
    AUTOMATED_TESTING: 1
  displayName: 'Build/Test (Linux)'

- script: |
    dzil test
  condition: startsWith(variables['IMAGE'], 'macos')
  env:
    RELEASE_TESTING: 1
    AUTOMATED_TESTING: 1
  displayName: 'Build/Test (macOS)'

